import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
await page.goto('http://127.0.0.1:3017', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
const gwTab = page.locator('.hdr-tabs .tab[data-app="gateway"]');
const out = [];
out.push('LED hidden:        ' + !(await page.locator('#gateway-led').isVisible()));
out.push('tab greyed:        ' + (await gwTab.evaluate((n) => n.classList.contains('unavailable'))));
await gwTab.click(); await page.waitForTimeout(300);
out.push('popover shown:     ' + (await page.locator('#gateway-dl-pop').isVisible()));
out.push('download link ok:  ' + ((await page.locator('#gateway-dl-pop .dl-btn').getAttribute('href')).includes('github.com')));
out.push('panel NOT shown:   ' + !(await page.locator('#gateway-app').isVisible()));
await page.locator('body').click({ position: { x: 400, y: 400 } }); await page.waitForTimeout(200);
out.push('popover dismissed: ' + !(await page.locator('#gateway-dl-pop').isVisible()));
console.log(out.join('\n'));
if (errors.length) console.log('PAGE ERRORS:\n' + errors.join('\n'));
await browser.close();
