import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
await page.goto('http://127.0.0.1:8799', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
const btn = page.locator('#transferBtn');
const out = [];
out.push('button un-greyed when bridged: ' + !(await btn.evaluate((n) => n.classList.contains('unavailable'))));
await page.locator('#editor').fill('(transfer smoke)\nG0 Z5\nM30\n');
await btn.click();
await page.waitForTimeout(800);
const toast = await page.locator('.toast').textContent().catch(() => '(no toast)');
out.push('toast: ' + toast);
const queue = await page.evaluate(async () => (await fetch('/api/queue')).json());
const job = queue.find((j) => (j.jobId || '').includes('transfer_smoke'));
out.push('job in queue: ' + !!job + (job ? ` (${job.jobId} state=${job.state || 'queued'})` : ''));
console.log(out.join('\n'));
if (errors.length) console.log('PAGE ERRORS:\n' + errors.join('\n'));
await browser.close();
