/**
 * ui/workspaceSave.js — INTENTIONAL SAVE (t1199; first-save flow t1225).
 *
 * Ctrl+S / a Save button writes the WHOLE workspace (.ddcs) to a USER-OWNED file via the File System Access API — the
 * deliberate "saved" act. localStorage stays the TEMPORARY buffer (persistence-A principle); only this writes a portable
 * file the user owns. Works on web AND the exe (pywebview → WebView2 exposes Chromium FSA).
 *
 * THE FIRST SAVE IS ONE STEP (t1225, user symptom: "Save produced a backup-style file"). Naming the workspace and
 * granting the workspaces FOLDER happen in the same flow, and the file is written INTO that folder — so the thing you
 * just saved is the thing the manager lists. A workspace is never given an autogenerated backup-style filename: the
 * name is always one the user typed, on every path including the no-FSA download fallback.
 *
 * Re-saving is silent: the file HANDLE is remembered (data/fsHandles.js), so a later Ctrl+S overwrites the SAME file
 * with no dialog — a real "Save". Opening a workspace RETARGETS that handle (see ui/workspaceManager.js), because a
 * save that still points at the previously-open file would silently overwrite it with someone else's contents.
 */
import { buildBackup, markWorkspaceSavedToFile, exportEverything, fileSavedName, fileSavedPlace } from '../data/backup.js';
import { setMachineName } from '../data/workspaceMachine.js';   // t1223 — saving names the workspace
import { getHandle, putHandle, requestHandle, handleGranted, FILE_KEY, FOLDER_KEY } from '../data/fsHandles.js';
import { dlgConfirm } from './dialog.js';

const canPickFile = () => typeof window !== 'undefined' && typeof window.showSaveFilePicker === 'function';
const canPickFolder = () => typeof window !== 'undefined' && typeof window.showDirectoryPicker === 'function';
const PICKER_OPTS = { types: [{ description: 'DDCS workspace', accept: { 'application/json': ['.ddcs'] } }] };

let handle = null;   // the current FSA file handle (this session; also persisted to IDB for cross-reload reuse)

const esc = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const stemOf = (s) => String(s || '').split(/[\\/]/).pop().replace(/\.ddcs$/i, '').trim();

/**
 * Point future Saves at THIS file — called when a workspace is OPENED. Passing null forgets the handle, which is the
 * honest state after opening a file that came from a plain <input type=file> (there is no handle to write back to), and
 * makes the next Save ask where to put it instead of overwriting whatever was open before.
 */
export async function adoptSaveHandle(h) {
    handle = h || null;
    await putHandle(FILE_KEY, h || null);
}

async function writeToHandle(h, text) { const w = await h.createWritable(); await w.write(text); await w.close(); }

/**
 * THE FIRST-SAVE / SAVE-AS FLOW — name + folder in ONE dialog.
 * Resolves { name, dir } (dir may be null when this browser cannot grant folders), or null if the user backs out.
 */
function askNameAndFolder(suggested, folder, place = 'local', { needsAllow = false } = {}) {
    return new Promise((resolve) => {
        let dir = folder, folderRefused = false, allow = needsAllow;
        // t1233 — a CLOUD save has no folder half: Drive's app folder is the one place, so the ask is just the name.
        const wantFolder = () => place !== 'cloud' && !dir && canPickFolder() && !folderRefused;
        const ov = document.createElement('div');
        ov.className = 'wss-ask';   // its OWN class — never `app-dialog`, which generic dialog drivers answer for you
        ov.id = 'wssAsk';
        ov.innerHTML = `<div class="wss-box">
            <div class="wss-title">Save this workspace</div>
            <label class="wss-lbl" for="wssName">Name</label>
            <div class="wss-namerow"><input id="wssName" class="wss-name" type="text" spellcheck="false" value="${esc(suggested)}"><span class="wss-ext">.ddcs</span></div>
            <div class="wss-folder" id="wssFolder"></div>
            <div class="wss-foot">
                <button type="button" class="toolbar-btn settings-io" data-wss="cancel">Cancel</button>
                <button type="button" class="toolbar-btn settings-io" data-wss="save" style="border-color:var(--accent);"></button>
            </div></div>`;
        const paint = () => {
            ov.querySelector('#wssFolder').innerHTML = place === 'cloud'
                ? '<span class="wss-dim">It will be saved to your Google Drive, in the DDCS Studio folder.</span>'
                : dir
                ? `<span class="wss-dim">Folder</span> <b>📁 ${esc(dir.name || 'workspaces')}</b>`
                  // t1263 — a REMEMBERED folder whose permission lapsed is not a missing folder. Say which it is, so
                  // the button below reads as "allow the folder you already chose" rather than "pick one again".
                  + (allow ? ' <span class="wss-dim">— this app needs your OK to use it again</span>' : '')
                  + (canPickFolder() ? ' <button type="button" class="wss-link" data-wss="folder">Change…</button>' : '')
                : (wantFolder()
                    ? '<span class="wss-dim">It will go in your workspaces folder — you pick that once, now.</span>'
                    : '<span class="wss-dim">No workspaces folder — this save will ask you where to put the file.</span>');
            ov.querySelector('[data-wss="save"]').textContent = wantFolder() ? 'Choose folder and save'
                : (allow ? 'Allow the folder and save' : '💾 Save');
        };
        const done = (v) => { ov.remove(); document.removeEventListener('keydown', onKey, true); resolve(v); };
        const onKey = (e) => {
            if (e.key === 'Escape') { e.preventDefault(); done(null); }
            if (e.key === 'Enter' && ov.contains(e.target)) { e.preventDefault(); commit(); }
        };
        const commit = async () => {
            const name = stemOf(ov.querySelector('#wssName').value);
            if (!name) { ov.querySelector('#wssName').focus(); return; }
            if (place === 'cloud') { done({ name, dir: null, place: 'cloud' }); return; }
            // t1263 — THE RE-ALLOW, inside the click that is a real user gesture. Same handle, no OS picker: the user
            // is confirming the folder they already chose. Only a denial here drops through to picking a new one.
            if (dir && allow) {
                if (await requestHandle(dir)) { allow = false; }
                else { dir = null; allow = false; folderRefused = false; paint(); return; }
            }
            if (wantFolder()) {
                // A REFUSED folder must never dead-end. Backing out of the OS folder dialog (or an environment that
                // refuses it outright — headless Chromium aborts it instantly, and so do some embedded webviews) used
                // to leave the user in a dialog whose only button silently did nothing. Now the ask simply drops the
                // folder half: it stays open, says so, and the same button becomes a plain Save.
                try { dir = await window.showDirectoryPicker({ mode: 'readwrite', id: 'ddcsWorkspaces' }); await putHandle(FOLDER_KEY, dir); }
                catch (_) { folderRefused = true; dir = null; }
                paint();
                if (!dir) return;
            }
            done({ name, dir });
        };
        ov.addEventListener('click', async (e) => {
            const b = e.target.closest('[data-wss]');
            if (!b) { if (e.target === ov) done(null); return; }
            if (b.dataset.wss === 'cancel') return done(null);
            if (b.dataset.wss === 'save') return commit();
            if (b.dataset.wss === 'folder') {
                try { dir = await window.showDirectoryPicker({ mode: 'readwrite', id: 'ddcsWorkspaces' }); await putHandle(FOLDER_KEY, dir); paint(); } catch (_) {}
            }
        });
        document.addEventListener('keydown', onKey, true);
        paint();
        document.body.appendChild(ov);
        const inp = ov.querySelector('#wssName');
        inp.focus(); inp.select();
    });
}

/** Get (or create) the file handle for `name` inside a granted folder, asking before replacing an existing file. */
async function fileInFolder(dir, name) {
    let existing = null;
    try { existing = await dir.getFileHandle(name); } catch (_) { existing = null; }
    if (existing) {
        let ok = false;
        try { ok = await dlgConfirm(`“${name}” already exists in ${dir.name || 'that folder'}. Replace it?`, { okLabel: 'Replace' }); }
        catch (_) { ok = false; }
        if (!ok) return null;
        return existing;
    }
    return dir.getFileHandle(name, { create: true });
}

/**
 * The deliberate save. `pickNew` forces the name+folder flow (Save As / Duplicate). `suggestedName` seeds it — that is
 * all Duplicate needs, because a duplicate IS a Save As under a different name over the same buildBackup bytes.
 * Returns {ok, name, viaFsa, aborted?}.
 */
export async function saveWorkspace({ pickNew = false, suggestedName = '', to = '' } = {}) {
    // t1233 — WHERE does this workspace live? An explicit `to` (the manager's active tab) wins; otherwise a plain Save
    // goes back where it came from, so a cloud workspace re-saves to the cloud with no dialog, exactly like a local one.
    const place = to || fileSavedPlace();
    if (place === 'cloud') return saveToCloud({ pickNew, suggestedName });

    // RE-SAVE: a remembered, still-permitted handle writes in place with no dialog at all.
    if (!pickNew && handle && await requestHandle(handle)) {
        try { return await writeTo(handle, handle.name || 'workspace.ddcs'); }
        catch (_) { /* the file moved / was revoked → fall through and ask again */ }
    }

    const suggested = stemOf(suggestedName) || stemOf(handle && handle.name) || stemOf(fileSavedName()) || 'workspace';
    // t1263 (user-proven) — DO NOT REQUEST PERMISSION HERE. This runs before the dialog opens, outside any user
    // gesture, and Chromium auto-denies an out-of-gesture request — so this line used to throw away a folder the user
    // had granted, on every launch, and send them back to the OS picker. Read the state with a QUERY and carry the
    // handle into the ask; the Save CLICK is a real gesture and re-requests it there (one Allow, no picker).
    const folder = await getHandle(FOLDER_KEY);
    const folderReady = folder ? await handleGranted(folder) : false;

    const picked = await askNameAndFolder(suggested, folder, 'local', { needsAllow: !!folder && !folderReady });
    if (!picked) return { ok: false, aborted: true };
    const fileName = picked.name + '.ddcs';

    if (picked.dir) {
        const h = await fileInFolder(picked.dir, fileName);
        if (!h) return { ok: false, aborted: true };   // declined the replace
        handle = h;
        await putHandle(FILE_KEY, h);
        return writeTo(h, fileName);
    }
    if (canPickFile()) {
        try {
            handle = await window.showSaveFilePicker({ ...PICKER_OPTS, suggestedName: fileName });
            await putHandle(FILE_KEY, handle);
            return await writeTo(handle, handle.name || fileName);
        } catch (e) {
            if (e && e.name === 'AbortError') return { ok: false, aborted: true };
        }
    }
    // TRUE no-FSA fallback: a download — but named the way the user named it, never a backup-style autogenerated stamp.
    try { setMachineName(fileName); } catch (_) {}
    await exportEverything(fileName);
    return { ok: true, name: fileName, viaFsa: false };
}

/**
 * SAVE TO THE CLOUD (t1233) — the same act, a different shelf.
 *
 * REUSED, not rebuilt: ui/cloud/googleDrive.js already had the whole Drive path (ensureRoot / write / the GIS token +
 * silent refresh) from the retired project-cloud doors. All this does is hand it a WHOLE .ddcs instead of a project
 * bundle — the bytes are the same buildBackup the local save writes, so a workspace is the same file wherever it sits.
 * The ORDER is the local one, for the same reason: name first, then bytes, then the save baseline.
 */
async function saveToCloud({ pickNew = false, suggestedName = '' } = {}) {
    let name = stemOf(suggestedName) || stemOf(fileSavedName());
    if (pickNew || !name) {
        const picked = await askNameAndFolder(name || 'workspace', null, 'cloud');
        if (!picked) return { ok: false, aborted: true };
        name = picked.name;
    }
    const fileName = name + '.ddcs';
    try {
        const drive = await import('./cloud/googleDrive.js');
        const root = await drive.ensureRoot();
        try { setMachineName(fileName); } catch (_) {}                 // 1. the file carries this file's name
        const obj = await buildBackup();                               // 2. build AFTER the stamp
        await drive.write(fileName, obj, root);
        markWorkspaceSavedToFile(fileName, 'cloud');                   // 3. baseline LAST, and it records WHERE
        return { ok: true, name: fileName, viaFsa: false, place: 'cloud' };
    } catch (e) {
        return { ok: false, error: (e && e.message) || String(e), place: 'cloud' };
    }
}

/**
 * Write the workspace to `h`. ORDER IS LOAD-BEARING (t1225): the name is stamped into the machine record BEFORE the
 * bytes are built, or the file carries the previous name; and the save baseline is marked AFTER the write, or the
 * workspace is dirty the instant it is saved (the name-stamp would land outside the baseline it is supposed to match).
 */
async function writeTo(h, name) {
    try { setMachineName(name); } catch (_) {}          // 1. the file's own machine record carries this file's name
    const text = JSON.stringify(await buildBackup(), null, 2);   // 2. build AFTER the stamp
    await writeToHandle(h, text);
    markWorkspaceSavedToFile(name);                     // 3. baseline LAST — it must cover the stamped name
    return { ok: true, name, viaFsa: true };
}

function onKeydown(e) {
    if (!(e.ctrlKey || e.metaKey) || e.altKey) return;
    if ((e.key || '').toLowerCase() !== 's') return;
    e.preventDefault();   // stop the browser's Save-Page dialog
    saveWorkspace({ pickNew: e.shiftKey }).catch(() => {});   // Ctrl+Shift+S = Save As
}

function install() {
    window.addEventListener('keydown', onKeydown);
    getHandle(FILE_KEY).then((h) => { if (h) handle = h; }).catch(() => {});   // restore the remembered file (permission re-checked on save)
    window.ddcsSaveWorkspace = saveWorkspace;
    window.ddcsAdoptSaveHandle = adoptSaveHandle;
    window.ddcsSaveHandleName = () => (handle && handle.name) || null;   // what the next silent Ctrl+S would overwrite
}

if (typeof window !== 'undefined') install();
