import { test, expect } from '@playwright/test';

// INTENTIONAL SAVE (t1199) — Ctrl+S / Save writes the WHOLE workspace (.ddcs) to a user-owned file via the File System
// Access API (the deliberate "saved" act; localStorage stays temporary). Headless Chromium has neither FSA picker, so
// the file path is exercised with an injected mock handle; the last test is the real default (no FSA → download).
//
// t1225 — a first save now ASKS for the name (and, where the browser can grant one, the workspaces folder) in one
// dialog before it touches the disk, so every test here answers that dialog. That is the point of it: a workspace is
// never written under an autogenerated backup-style name, on any path — including the download fallback.
test.use({ viewport: { width: 1400, height: 900 } });

// Install a mock FSA picker returning a fake handle that captures every write. window.__pickCount tracks re-picks.
const MOCK_FSA = () => {
  window.__written = [];
  window.__pickCount = 0;
  window.showSaveFilePicker = async () => {
    window.__pickCount++;
    return {
      name: 'my-workspace.ddcs',
      createWritable: async () => ({ write: async (t) => { window.__written.push(t); }, close: async () => {} }),
      queryPermission: async () => 'granted',
      requestPermission: async () => 'granted',
    };
  };
};

async function ready(page) {
  await page.goto('http://localhost:3211');
  await page.waitForFunction(() => window.ddcsSaveWorkspace && window.ddcsFileSavedAt && window.ddcsFileSavedName);
}

/**
 * Answer the first-save ask: type the name, then confirm.
 *
 * Headless Chromium HAS showDirectoryPicker but ABORTS it instantly, so this exercises the refused-folder path for
 * real: the ask does not dead-end, it drops the folder half and its button becomes a plain Save — one more click.
 */
async function answerSaveAsk(page, name = 'my-workspace') {
  await page.waitForSelector('#wssAsk', { timeout: 8000 });
  await page.fill('#wssName', name);
  await page.locator('#wssAsk [data-wss="save"]').click();
  await page.waitForFunction(() => { const b = document.querySelector('#wssAsk [data-wss="save"]'); return !b || !/Choose/i.test(b.textContent); }, null, { timeout: 8000 });
  if (await page.locator('#wssAsk').count()) await page.locator('#wssAsk [data-wss="save"]').click();
}

test('FSA save writes the workspace to a user-owned file, reuses the handle, and the disk reads saved + names the file', async ({ page }) => {
  await ready(page);
  await page.evaluate(MOCK_FSA);

  const saving = page.evaluate(async () => {
    const r = await window.ddcsSaveWorkspace();
    return { r, picks: window.__pickCount, wrote: window.__written.length, body: window.__written[0] || '', savedAt: window.ddcsFileSavedAt(), name: window.ddcsFileSavedName() };
  });
  await answerSaveAsk(page);
  const first = await saving;
  expect(first.r.viaFsa, 'used the File System Access path').toBe(true);
  expect(first.picks, 'the picker was shown once (first save)').toBe(1);
  expect(first.body, 'the whole workspace backup was written to the file').toContain('ddcs.backup');
  expect(first.savedAt, 'a real file save stamps the time').toBeGreaterThan(0);
  expect(first.name, 'the saved filename is recorded').toBe('my-workspace.ddcs');

  // a SECOND save reuses the SAME handle — a real "Save", not "Save As" every time, and it asks NOTHING
  const second = await page.evaluate(async () => { await window.ddcsSaveWorkspace(); return { picks: window.__pickCount, wrote: window.__written.length, asked: !!document.getElementById('wssAsk') }; });
  expect(second.picks, 'no re-pick on the second save (handle reused)').toBe(1);
  expect(second.wrote, 'the file was written again').toBe(2);
  expect(second.asked, 'and no dialog: a re-save is silent').toBe(false);

  // the persistence-A chip reflects the filename
  // t1223 — the indicator is a disk BUTTON: the state is its colour class, and the filename lives in the tooltip.
  const chip = await page.evaluate(() => { const c = document.getElementById('fileSaveChip'); return { saved: c.classList.contains('saved'), title: c.title, label: c.textContent.trim() }; });
  expect(chip.saved, 'the disk goes muted/saved').toBe(true);
  expect(chip.title, 'and its tooltip names the file').toContain('my-workspace.ddcs');
  expect(chip.label, 'with no label beside the icon').toBe('');
});

test('Ctrl+S triggers the workspace save (Ctrl+Shift+S forces a re-pick = Save As)', async ({ page }) => {
  await ready(page);
  await page.evaluate(MOCK_FSA);

  await page.evaluate(() => window.dispatchEvent(new KeyboardEvent('keydown', { key: 's', ctrlKey: true, cancelable: true })));
  await answerSaveAsk(page);
  await page.waitForFunction(() => window.__written && window.__written.length >= 1, null, { timeout: 5000 });
  expect(await page.evaluate(() => window.__pickCount)).toBe(1);

  // Ctrl+Shift+S = Save As → asks again (a new name) even though a handle exists
  await page.evaluate(() => window.dispatchEvent(new KeyboardEvent('keydown', { key: 's', ctrlKey: true, shiftKey: true, cancelable: true })));
  await answerSaveAsk(page, 'a-copy');
  // wait for the WRITE, not the pick: the picker resolves first, then the backup is built and written (both async)
  await page.waitForFunction(() => window.__written.length >= 2, null, { timeout: 5000 });
  expect(await page.evaluate(() => window.__pickCount), 'Save As re-picked even though a handle existed').toBe(2);
});

test('without FSA it falls back to a download — named what the user typed, never an autogenerated stamp', async ({ page }) => {
  await ready(page);
  // simulate a browser without the File System Access API (Firefox / older Safari) → the download fallback
  await page.evaluate(() => { window.showSaveFilePicker = undefined; window.showDirectoryPicker = undefined; });
  expect(await page.evaluate(() => typeof window.showSaveFilePicker !== 'function'), 'FSA unset for the fallback path').toBe(true);

  const [download] = await Promise.all([
    page.waitForEvent('download', { timeout: 8000 }),
    page.evaluate(() => window.ddcsSaveWorkspace()),
    answerSaveAsk(page, 'bench-router'),
  ]);
  expect(download.suggestedFilename(), 'the download carries the name the user typed').toBe('bench-router.ddcs');
  expect(download.suggestedFilename(), 'not a backup-style autogenerated one').not.toMatch(/^ddcs-workspace-/);
  expect(await page.evaluate(() => window.ddcsFileSavedAt()), 'the download still marks the workspace saved').toBeGreaterThan(0);
  expect(await page.evaluate(() => window.ddcsFileSavedName()), 'and the workspace remembers its name').toBe('bench-router.ddcs');
});
