#!/usr/bin/env python3
"""
release.py — local release helper for DDCS-Studio.

Usage:
    python release.py                       # Claude CLI auto-generates commit message from staged diff
    python release.py "commit message"      # explicit override

Steps:
  1. git add -A; (auto-generate message if none given); commit; push
       (Cloudflare Pages auto-rebuilds the web app on push to main)

Auto-generated commit messages shell out to the `claude` CLI in print
mode. No API key needed — uses your existing Claude Code auth. If the
CLI is missing or the call fails, falls back to a comma-separated list
of changed file basenames. If that also fails, prompts interactively.
"""

import os
import shutil
import subprocess
import sys

sys.stdout.reconfigure(encoding='utf-8', errors='replace')

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
PAGES_URL = "https://ddcs-studio.pages.dev"

commit_summary = "(skipped)"
commit_message_summary = "(none)"
push_summary = "(skipped)"

commit_message = sys.argv[1].strip() if len(sys.argv) >= 2 else ""


def _generate_commit_message_via_claude_cli():
    """Shell out to `claude -p` with the staged diff. Returns the message, or None on failure."""
    claude_cmd = shutil.which("claude") or shutil.which("claude.cmd")
    if not claude_cmd:
        print("      Note: `claude` CLI not on PATH; skipping AI message generation.")
        return None

    diff = subprocess.run(
        ["git", "diff", "--cached", "--no-color"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    ).stdout
    if not diff.strip():
        return None

    MAX_DIFF_CHARS = 50000
    if len(diff) > MAX_DIFF_CHARS:
        diff = diff[:MAX_DIFF_CHARS] + "\n[... diff truncated]"

    prompt = (
        "Write a single-line git commit message for the following diff. "
        "Use conventional commit style (e.g. 'fix:', 'feat:', 'docs:', 'refactor:', 'chore:'). "
        "Keep it under 72 characters. "
        "Output ONLY the message itself — no quotes, no explanation, no markdown.\n\n"
        f"```diff\n{diff}\n```"
    )

    print("      Asking `claude` for a commit message (may take 3-5s)...")
    try:
        result = subprocess.run(
            [claude_cmd, "-p", prompt],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=120,
        )
    except subprocess.TimeoutExpired:
        print("      Claude CLI timed out.")
        return None
    except Exception as e:
        print(f"      Claude CLI invocation failed: {e}")
        return None

    if result.returncode != 0:
        print(f"      Claude CLI exited {result.returncode}: {result.stderr.strip()[:200]}")
        return None

    msg = result.stdout.strip()
    for ch in ('"', "'", "`"):
        if msg.startswith(ch) and msg.endswith(ch):
            msg = msg[1:-1].strip()
    msg = msg.split("\n")[0].strip()
    return msg or None


def _generate_fallback_message_from_diff():
    """Compose a commit message from the list of staged file basenames."""
    result = subprocess.run(
        ["git", "diff", "--cached", "--name-only"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    )
    files = [line.strip() for line in result.stdout.splitlines() if line.strip()]
    if not files:
        return None
    basenames = [os.path.basename(f) for f in files]
    msg = "update: " + ", ".join(basenames)
    if len(msg) > 120:
        msg = msg[:117] + "..."
    return msg


# ----- commit + push -----------------------------------------------------
print("[1/1] Committing and pushing...")
subprocess.run(["git", "add", "-A"], cwd=REPO_ROOT, check=True)

status = subprocess.run(["git", "status", "--porcelain"], cwd=REPO_ROOT,
                        capture_output=True, text=True, check=True)
if status.stdout.strip():
    if not commit_message:
        commit_message = _generate_commit_message_via_claude_cli()
        if commit_message:
            print(f"      Generated by Claude: {commit_message}")
        else:
            commit_message = _generate_fallback_message_from_diff()
            if commit_message:
                print(f"      Fallback (file list): {commit_message}")
            else:
                try:
                    commit_message = input("      Enter commit message: ").strip()
                except (EOFError, KeyboardInterrupt):
                    commit_message = ""
                if not commit_message:
                    print("      No message provided; aborting.")
                    sys.exit(1)

    commit = subprocess.run(["git", "commit", "-m", commit_message], cwd=REPO_ROOT)
    if commit.returncode != 0:
        print(f"      git commit failed (exit {commit.returncode}). Aborting.")
        sys.exit(commit.returncode)
    sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=REPO_ROOT,
                         capture_output=True, text=True).stdout.strip()
    commit_summary = sha
    commit_message_summary = commit_message
else:
    print("      No staged changes; skipping commit.")
    commit_summary = "(no-op, nothing to commit)"
    commit_message_summary = "(none)"

push = subprocess.run(["git", "push"], cwd=REPO_ROOT)
if push.returncode != 0:
    print(f"      git push failed (exit {push.returncode}). Aborting.")
    sys.exit(push.returncode)
branch = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=REPO_ROOT,
                        capture_output=True, text=True).stdout.strip()
push_summary = f"{branch} -> origin/{branch}"
print("      Pushed. Cloudflare Pages will auto-rebuild the web app.")


# ----- summary ----------------------------------------------------------
print()
print("=" * 64)
print("  Release Summary")
print("=" * 64)
print(f"  Commit:     {commit_summary}")
print(f"  Message:    {commit_message_summary}")
print(f"  Push:       {push_summary}")
print(f"  Web app:    {PAGES_URL}  (Cloudflare rebuilds on push)")
print("=" * 64)
