#!/usr/bin/env node
// import_vars.js (ES module)
// Usage: node import_vars.js --input "Variables-ENG 01-04-2025.csv" --output default_vars.js

import fs from 'fs/promises';
import { existsSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DEFAULT_INPUT = 'Variables-ENG 01-04-2025.csv';
const DEFAULT_OUTPUT = 'default_vars.js';

function parseCSV(text) {
    const rows = [];
    let field = '';
    let row = [];
    let inQuotes = false;

    for (let i = 0; i < text.length; i++) {
        const ch = text[i];

        if (ch === '"') {
            // Escaped quote (double double-quote) -> append a quote
            if (inQuotes && text[i + 1] === '"') {
                field += '"';
                i++; // skip the escaped quote
            } else {
                inQuotes = !inQuotes; // toggle
            }
        } else if (ch === ',' && !inQuotes) {
            row.push(field);
            field = '';
        } else if ((ch === '\n' || ch === '\r') && !inQuotes) {
            if (ch === '\n') {
                row.push(field);
                rows.push(row);
                field = '';
                row = [];
            }
        } else {
            field += ch;
        }
    }

    if (field !== '' || row.length > 0) {
        row.push(field);
        rows.push(row);
    }

    return rows.map(r => r.map(f => {
        if (typeof f !== 'string') return '';
        let s = f.replace(/\r/g, '').replace(/\n/g, ' ').trim();
        if (s.startsWith('"') && s.endsWith('"')) s = s.slice(1, -1);
        s = s.replace(/""/g, '"');
        return s;
    }));
}

function usage() {
    console.log('Usage: node import_vars.js [--input FILE] [--output FILE]');
}

async function main(argv = process.argv.slice(2)) {
    try {
        let input = DEFAULT_INPUT;
        let output = DEFAULT_OUTPUT;

        for (let i = 0; i < argv.length; i++) {
            const a = argv[i];
            if (a === '-i' || a === '--input') input = argv[++i];
            else if (a === '-o' || a === '--output') output = argv[++i];
            else if (a === '-h' || a === '--help') { usage(); return 0; }
        }

        const absInput = path.resolve(process.cwd(), input);
        const absOutput = path.resolve(process.cwd(), output);

        if (!existsSync(absInput)) {
            console.error(`Input file not found: ${absInput}`);
            return 2;
        }

        const raw = await fs.readFile(absInput, { encoding: 'utf8' });
        const rows = parseCSV(raw);

        // Keep rows where first column starts with a digit
        const cleaned = [];
        for (const r of rows) {
            if (!r || r.length === 0) continue;
            const id = (r[0] || '').trim();
            if (!/^[0-9]/.test(id)) continue;

            const permission = (r[1] || '').trim();
            const description = (r[2] || '').trim();
            const notes = (r[3] || '').trim();

            const safeDescription = description.replace(/`/g, '\\`');
            const safeNotes = notes.replace(/`/g, '\\`');

            // Always output four columns (notes may be empty)
            cleaned.push(`${id},${permission},${safeDescription},${safeNotes}`);
        }

        const now = new Date().toISOString();
        const header = `// Generated by import_vars.js on ${now}\n// Source: ${path.basename(absInput)}\n`;

        const fileContent = `${header}export const DEFAULT_VAR_CSV = ` + '`\n' + cleaned.join('\n') + '\n`;' + '\n';

        await fs.writeFile(absOutput, fileContent, { encoding: 'utf8' });

        console.log(`SUCCESS: written ${cleaned.length} entries to ${absOutput}`);
        return 0;
    } catch (err) {
        console.error('FAILED:', err && err.message ? err.message : err);
        return 1;
    }
}

// Run when executed directly
if (process.argv && process.argv.length > 1) {
    // If running as a script, execute main
    main().then(code => { if (code && code !== 0) process.exit(code); });
}
