/**
 * blocks/dataOps/atcChangeData.js — the ATC TOOL CHANGE built-in as a pure DATA definition (E1, t564; on the E0 superset
 * 42c4ff9). The HARDEST of the ATC set.
 *
 * atc_change routes (method × callMacro) into 5 DISTINCT arms — m6 / manual / macroCall (T# M6 call) / firmware (O10102 push) /
 * inlineTnc (the live-settings tncProgram body). The E0 superset carries all 5 GUARDED by the DERIVED `_arm` key. The twin:
 *   • deriveGuards injects `_arm` (via atcChangeEffectiveArm) so pruneGuards collapses the template to the routed arm.
 *   • postInstantiate is the M2 transform-in-place recompose:
 *       - the STATIC arms (m6/manual/macroCall/firmware) VALUE-SWAP their param-derived lines by ROLE in place (assign by
 *         var · mcode by code · comment/raw/message/confirm by number-stripped text) — a user's added atom SURVIVES; a shape
 *         TOGGLE (fixedT 0↔>0 → the T-word comment; orient on↔off → the M19) takes the arm WHOLESALE from fresh (the gap).
 *       - the inlineTnc arm is a DECLARED LIVE-VIEW: it REGENERATES wholesale from live settings.atc + ATC I/O at every
 *         instantiation (the fork ruling — the codes stay out of the marker, always fresh). DOCUMENTED GAP: user edits inside
 *         the live arm do NOT survive (it is a view of the current settings, re-derived every emit).
 *   • firmware's controller-taught vars (#1306 / #1320-1326) stay LITERAL register references — they are the controller's, not
 *     op params, so they ride through unchanged (never bound).
 *
 * NOT registered/opened in-place yet (E2). Byte-identical to atcChangeStack across the method × callMacro × config sweep.
 */
import { atcChangeStack, atcChangeEffectiveArm } from '../../wizards/stacks/atcChangeWizard.js';
import { userOpFromStack } from '../userOps.js';
import { atcCombo } from '../../wizards/atcModel.js';
import { motionToSimGcode, interpCtxFromAtc } from '../../wizards/atcInterpreter.js';
import { magazinePockets } from '../../wizards/views/atcViews.js';   // the shared 3D-magazine pocket list (linear + disk)

export const ATC_CHANGE_DATA_OPTYPE = 'user_atc_change_data';

/** Author defaults — MIRROR the run-form fields (the twin-default rule): the atc_change panel's own defaults (m6 · call T.nc ·
 *  park/change 100,100,0 · Z-change 0 · tool-from-program · M19 orient ON). The magazine + ATC I/O codes are NOT form fields —
 *  they are live settings, read + regenerated by the inlineTnc arm at instantiation. */
export const ATC_CHANGE_DEFAULTS = { method: 'm6', callMacro: true, x: 100, y: 100, z: 0, zClear: 0, fixedT: 0, orient: true };

/** The op params (the run-form): the METHOD picker + the callMacro toggle (the two routing drivers) + the scalars each arm
 *  uses. All FORM fields (no value socket — the recompose bakes every value from the routed arm via atcChangeStack). The
 *  per-method gating (which fields a method honours) lands in E2. */
// t2383 — SECTION MISMATCH, fixed: the shell (index.html:972-1033) declares exactly ONE section-label —
// "TOOL CHANGE" — covering every visible field, differentiated only by conditional show/hide `<div>`s per
// method (never a second section header). This array previously invented THREE names (METHOD/POSITION/
// FIRMWARE) that appear nowhere in the shell. Collapsed to the shell's own single name for every entry —
// same governing rule as t2375's contour fix (the declaration reproduces the shell exactly, never tidies).
// ALSO reordered: the shell's own DOM order is `_setup` (the "⚙ ATC Settings…" button, index.html:983 —
// BEFORE the "TOOL CHANGE" label itself) → method → callMacro → x/y/z (manual) → zClear/fixedT (m6, in
// THAT order — zclear at line 1008, fixedt at 1009) → orient (firmware). This array had fixedT BEFORE
// x/y/z/zClear — live-caught (window.openWiz('atc_change'), the default m6 state) as a real field-order
// mismatch, not just a section-name one.
// NOT fixed here (a SEPARATE, larger gap, out of this turn's own section-metadata scope, and the file's own
// header comment already names it as deliberately deferred — "per-method gating... lands in E2"): the shell
// ALSO has three AUTO-method checkboxes (m300/cover/confirm) with no binding here at all. Recorded, not added.
const AUTO = ['firmware', 'generic', 'disk'];   // the AUTOMATIC methods (the gating pivot)
export const ATC_CHANGE_STRUCT_BINDINGS = [
    // t566 — the "ATC Settings…" button (an action widget; contributes no param) opens Settings → ATC (magazine, drawbar I/O, changer).
    { param: '_setup', type: 'bool', widget: 'action', action: 'atcSettings', default: false, label: 'ATC Settings…', help: 'Open Settings → ATC: the magazine, the drawbar / sensor I/O, and the changer model the automatic methods use.', section: 'TOOL CHANGE' },
    { param: 'method', type: 'enum', widget: 'dropdown', default: ATC_CHANGE_DEFAULTS.method, label: 'Method', help: 'How the tool change happens: delegate to the controller (M6), a manual hand swap, the firmware push station (O10102), or an inline magazine / disk change.', section: 'TOOL CHANGE', widgetConfig: { options: [['Delegate to controller (M6)', 'm6'], ['Manual (hand swap)', 'manual'], ['Firmware push (O10102)', 'firmware'], ['Magazine pick & place', 'generic'], ['Disk carousel', 'disk']] } },
    // callMacro only applies to the AUTOMATIC methods (T# M6 call ↔ inline fallback) → shown only there.
    { param: 'callMacro', type: 'bool', default: ATC_CHANGE_DEFAULTS.callMacro, label: 'Call installed T.nc', help: 'Automatic methods call your installed T.nc (T# M6); uncheck for the inline offline fallback (sources Settings → ATC I/O).', section: 'TOOL CHANGE', when: { param: 'method', in: AUTO } },
    { param: 'x', type: 'number', default: ATC_CHANGE_DEFAULTS.x, label: 'Change / Park X', help: 'The MACHINE X the head parks at for the change.', section: 'TOOL CHANGE' },
    { param: 'y', type: 'number', default: ATC_CHANGE_DEFAULTS.y, label: 'Change / Park Y', help: 'The MACHINE Y the head parks at for the change.', section: 'TOOL CHANGE' },
    // Park Z is only the MANUAL hand-swap retract.
    { param: 'z', type: 'number', default: ATC_CHANGE_DEFAULTS.z, label: 'Park Z', help: 'The MACHINE Z the head retracts to for a manual swap.', section: 'TOOL CHANGE', when: { param: 'method', is: 'manual' } },
    // Z change height feeds only the M6-delegate; auto methods use the machine Safe Z (Settings → ATC) → greyed for auto.
    { param: 'zClear', type: 'number', default: ATC_CHANGE_DEFAULTS.zClear, label: 'Z change height', help: 'The MACHINE Z the M6-delegate retracts to before the change (automatic methods use the machine Safe Z).', section: 'TOOL CHANGE', gate: { param: 'method', in: AUTO, tip: 'The automatic tool change uses your machine Safe Z (Settings → ATC). Z change height applies to the M6-delegate method.' } },
    // fixedT is GREYED for auto+inline: the inline body can't set the requested tool (#1504 is a Tn M6 register).
    { param: 'fixedT', type: 'number', default: ATC_CHANGE_DEFAULTS.fixedT, label: 'Change to tool', help: 'The target tool number (0 = the tool from a preceding program Txx).', section: 'TOOL CHANGE', gate: { all: [{ param: 'method', in: AUTO }, { param: 'callMacro', is: false }], tip: 'Inline mode can’t set the requested tool — the DDCS #1504 register is populated by a Tn M6 call, not written inline. Use the recommended “Call installed T.nc macro” mode to change to a specific tool, or select it in your program.' } },
    // M19 orient is only the FIRMWARE push.
    { param: 'orient', type: 'bool', default: ATC_CHANGE_DEFAULTS.orient, label: 'M19 orient before unclamp', help: 'Orient the spindle (M19) before the firmware push unclamps.', section: 'TOOL CHANGE', when: { param: 'method', is: 'firmware' } },
];

// t2603 (BACKLOG #71/#72/#77) — `atcChangeDataStack()` (the old flat-render `user_root` wrapper) is REMOVED
// here — `atcChangeDataDef()` below now builds its own tree-shaped stack inline, and grepping the whole repo
// found no other caller (product code or test) invoking this function by name.

/** The DERIVED guard key — the EFFECTIVE arm (from method × callMacro), so pruneGuards collapses the superset to the routed
 *  arm. ONE source with the concrete build (atcChangeEffectiveArm). */
export function atcChangeDeriveGuards(p) { return { _arm: atcChangeEffectiveArm(p) }; }

// The number-stripped text (so a param-derived line's role is STABLE across a value change: "Change to T4" ~ "Change to T7"
// → "Change to T#"). Roles anchor the edit-graft; a user-added atom's role is in NEITHER fresh NOR canonical(DEFAULTS) → it is
// the edit to re-graft.
const strip = (t) => String(t == null ? '' : t).replace(/-?\d+(\.\d+)?/g, '#');

// The ROLE of a role-bearing line (stable across value changes) — the anchor for the edit-graft. Structural atoms
// (spindle/coolant/machinemove/pause/label/goto/…) reference vars, not values → null (not anchors; a null-role user edit is a
// documented gap — the common edits are role-bearing comments / M-codes).
function derivedRole(b) {
    if (!b || !b.params) return null;
    if (b.type === 'assign') return 'A:' + (b.params.var || '');
    if (b.type === 'mcode') return 'M:' + (b.params.code != null ? b.params.code : '');
    if (b.type === 'comment') return 'C:' + strip(b.params.text);
    if (b.type === 'raw') return 'R:' + strip(b.params.text);
    if (b.type === 'message') return 'MSG:' + strip(b.params.text);
    if (b.type === 'confirm') return 'CF:' + strip(b.params.msg);
    return null;
}

/**
 * The M2 STATIC-ARM MERGE — take the FRESH arm WHOLESALE (canonical structure + the CURRENT param values → byte-identical to
 * atcChangeStack, and toggles like fixedT 0↔>0 / orient just work), then RE-GRAFT the user's added atoms. A stored block is a
 * USER EDIT iff its role is in NEITHER fresh(resolved) NOR canonical(DEFAULTS) — so on a FRESH build (stored == canonical
 * (DEFAULTS)) NOTHING is grafted (pure fresh = byte-identical), while a user-added comment/M-code (a novel role) IS. Each edit
 * is re-inserted after its preceding canonical anchor. Value-edits to a canonical block are form-driven (fresh wins); a
 * null-role edit (a bare move/pause) or an edit whose anchor toggled away is the documented gap.
 */
function mergeStaticArm(stored, resolved) {
    const fresh = atcChangeStack(resolved, {});
    const dflt = atcChangeStack({ ...ATC_CHANGE_DEFAULTS, method: resolved.method, callMacro: resolved.callMacro }, {});   // canonical(DEFAULTS) for the SAME arm
    const canon = new Set([...fresh, ...dflt].map(derivedRole).filter(Boolean));
    const edits = []; let anchor = null;
    for (const b of stored) {
        const r = derivedRole(b);
        if (r == null) continue;                       // structural (moves/spindle/pause) — not an anchor, not a graftable edit
        if (canon.has(r)) { anchor = r; continue; }    // canonical role → an anchor
        edits.push({ block: b, after: anchor });       // a novel role → a user edit; graft it after the last canonical anchor
    }
    const out = edits.filter((e) => e.after == null).map((e) => e.block);   // edits before any anchor → prepend
    for (const b of fresh) {
        out.push(b);
        const r = derivedRole(b);
        if (r) for (const e of edits) if (e.after === r) out.push(e.block);
    }
    return out;
}

/**
 * The M2 EMIT RECOMPOSE (t550 ruling) — operate on the OP'S OWN STORED body. The routed arm is regenerated from the CURRENT
 * settings via atcChangeStack (the ONE source). The inlineTnc arm is a DECLARED LIVE-VIEW (regenerated wholesale — edits do
 * NOT survive). A STATIC arm takes the fresh (value-tracked) structure + re-grafts user edits (they survive).
 */
function applyAtcChangeRecompose(stack, resolved) {
    const root = (Array.isArray(stack) ? stack : []).find((b) => b && b.type === 'user_root');
    if (!root || !Array.isArray(root.children)) return stack;
    const arm = atcChangeEffectiveArm(resolved);
    if (arm === 'inlineTnc') { root.children = atcChangeStack(resolved, {}); return stack; }   // declared live-view → regenerate wholesale (edits don't survive)
    root.children = mergeStaticArm(root.children, resolved);   // static arm: fresh values + re-grafted user edits (edits survive)
    return stack;
}

/** Build the tool-change-as-data def — the E0 superset template + deriveGuards (the routed arm) + the M2 recompose in
 *  postInstantiate. Byte-identical to atcChangeStack across the method × callMacro × config sweep. NO opensAs yet (E2). */
export function atcChangeDataDef() {
    // t2603 (BACKLOG #71/#72, Phase 1 step 1) — no value bindings (every param is a plain form field, no
    // blockIndex/match), so no two-phase derive is needed — same shape as homing/atc_table/atc_test. ONE
    // group_box (the shell's own single section, "TOOL CHANGE").
    const fieldRefsOf = (group) => group.map((b) => ({ type: 'field_ref', params: { param: b.param } }));
    const stack = [{
        type: 'user_root',
        params: {},
        uiChildren: [{
            // t2603 (Phase 1 step 1) — wrapped in split_horizontal so hasTreeLayout() (userOpView.js) routes
            // this twin onto renderUiTree, the SAME mechanism drill/surfacing/bore/.../atc_table/atc_test
            // already use. Like those two, atc_change's own CLASSIC shell (`#wiz_atc_change`, index.html:996)
            // is NOT retired — a real, separate, currently-live UI (atcViews.js's own panel class); this twin
            // is simply "NOT registered/opened in-place yet (E2)" per this file's own header. No usage_text
            // precedent to reproduce from that shell — written fresh.
            type: 'split_horizontal', params: { ratio: '360px:*' },
            children: {
                LEFT: [{
                    type: 'param_group',
                    params: { group: 'Tool Change' },
                    children: [
                        { type: 'usage_text', params: { text: 'How the tool change happens: delegate to the controller (M6), a manual hand swap, the firmware push station, or an inline magazine/disk change. Automatic methods call your installed T.nc macro by default; uncheck to source Settings → ATC I/O inline instead.' } },
                        { type: 'group_box', params: { title: 'TOOL CHANGE' }, children: fieldRefsOf(ATC_CHANGE_STRUCT_BINDINGS) },
                        { type: 'code_preview', params: { tag: '(DDCS M350 COMPLIANT)' } },
                    ],
                }],
                // t2603 (Phase 1 step 2) — panel='form3d' (no 2D pane). preview3d declared ALONE — the SAME
                // shape BACKLOG #77 found broken and t2603 fixed. Verified via atc_table's own row-diff +
                // targeted suite first; this op shares the identical mechanism, not re-verified from scratch.
                RIGHT: [
                    { type: 'preview3d', params: { rotary: false, magazine: true, toolMachine: true } },
                ],
            },
        }],
        children: atcChangeStack(ATC_CHANGE_DEFAULTS, { superset: true }),
    }];
    const def = userOpFromStack('atc_change_data', 'Tool Change (data)', stack, [...ATC_CHANGE_STRUCT_BINDINGS], 'form3d', { forceMachine: true, showMagazine: true, toolMachineFrame: true }, 'atc_datawiz');
    def.deriveGuards = atcChangeDeriveGuards;
    def.postInstantiate = (stack, resolved) => applyAtcChangeRecompose(stack, resolved);
    // t566 — the CHOREOGRAPHY sim: the AUTOMATIC methods emit a bare `T# M6` (macroCall) or the inline body, but the preview
    // animates the interpreter's assumed pick&place / push motion (the legacy atcChangeView path). m6/manual → null → the
    // real emit's own moves animate. Read live settings; the machine + magazine tiles come from the declared sim intent.
    def.simGcode = (params) => {
        const s = (typeof window !== 'undefined' && window.ddcsGetSettings && window.ddcsGetSettings()) || {};
        const cmb = atcCombo(params, s.atc);
        const interpret = !!(cmb && cmb.motion && (cmb.motion.candidate || ['firmware', 'generic', 'disk'].includes(cmb.method)));
        if (!interpret) return null;
        try { return motionToSimGcode(cmb, interpCtxFromAtc(s.atc || {}, magazinePockets(s.atc || {}), { outputs: s.outputs || [], inputs: s.inputs || [] })); }
        catch (_) { return null; }
    };
    return def;
}
